/**
 * Report generator. FR6: runs the first time a campaign reaches severity >= 4
 * or >= 5 events. Deterministic and LLM-free so it works on the free tier —
 * the narrative is templated from stored facts, not invented.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Campaign, EnrichedEvent } from "./schemas";
import {
  getCampaign,
  getCampaignEvents,
  markReportGenerated,
  needsReport,
} from "./store";

const OUT_DIR = process.env.REPORT_DIR ?? "reports";

const SEVERITY_LABEL: Record<number, string> = {
  1: "Informational",
  2: "Low",
  3: "Medium",
  4: "High",
  5: "Critical",
};

const CLASS_LABEL: Record<string, string> = {
  noise: "Background noise",
  recon: "Reconnaissance",
  credential_stuffing: "Credential stuffing",
  active_exploit_attempt: "Active exploitation attempt",
};

function esc(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

export function renderReport(c: Campaign, events: EnrichedEvent[]): string {
  const usernames = [
    ...new Set(events.map((e) => e.usernameTried).filter(Boolean)),
  ] as string[];
  const passwords = [
    ...new Set(events.map((e) => e.passwordTried).filter(Boolean)),
  ] as string[];
  const commands = [
    ...new Set(events.flatMap((e) => e.commandsAttempted ?? [])),
  ];
  const countries = [
    ...new Set(events.map((e) => e.geo?.country).filter(Boolean)),
  ] as string[];

  const timeline = events
    .map(
      (e) =>
        `| ${e.timestamp} | ${esc(String(e.usernameTried ?? "-"))} | ${esc(
          String(e.passwordTried ?? "-"),
        )} | ${e.commandsAttempted?.length ?? 0} | ${e.classification} | ${e.severity} |`,
    )
    .join("\n");

  return `# Incident Report — Campaign \`${c.id}\`

**Severity:** ${SEVERITY_LABEL[c.maxSeverity]} (${c.maxSeverity}/5)
**Status:** ${c.status}
**Events:** ${events.length}
**First seen:** ${c.firstSeen}
**Last seen:** ${c.lastSeen}

## Summary

${events.length} SSH session${events.length === 1 ? " was" : "s were"} recorded against the honeypot from ${c.sourceIps.length} source address${c.sourceIps.length === 1 ? "" : "es"} and classified as **${CLASS_LABEL[events[0]?.classification ?? "noise"] ?? events[0]?.classification}** at up to severity ${c.maxSeverity}/5.

${
  c.maxSeverity >= 4
    ? "This campaign crossed the escalation threshold and warrants analyst review."
    : "This campaign is below the escalation threshold and is recorded for trending only."
}

## In plain language

${
  c.maxSeverity >= 4
    ? `Someone tried to get into the decoy server and pushed past simple password guessing. ` +
      `They logged in with common credentials and then started running system commands to ` +
      `understand what the machine was and what it was running. No real system was harmed — ` +
      `every command was recorded and answered with canned replies, never executed.`
    : `Automated background traffic touched the decoy server. It logged in with common ` +
      `credentials and browsed around, but showed no sign of moving toward exploitation. ` +
      `This is the normal background patter of the public internet.`
}

## Indicators of compromise (IOCs)

**Source IPs**

${c.sourceIps.map((ip) => `- \`${ip}\``).join("\n")}

**Usernames attempted**

${usernames.length ? usernames.map((u) => `- \`${u}\``).join("\n") : "- none recorded"}

**Passwords attempted**

${passwords.length ? passwords.map((p) => `- \`${p}\``).join("\n") : "- none recorded"}

**Commands attempted**

${commands.length ? commands.map((cmd) => `- \`${esc(cmd)}\``).join("\n") : "- none recorded"}

**Origin**

${countries.length ? countries.join(", ") : "unavailable (no geolocation data for these source IPs)"}

## Timeline

| Timestamp | Username | Password | Cmds | Classification | Sev |
| --- | --- | --- | --- | --- | --- |
${timeline}

---
_Generated by the AI SOC Analyst. All attacker commands were recorded and simulated; none were executed._
`;
}

/** Generate and persist a report if the campaign has crossed the threshold. */
/**
 * FR6: generate when severity >= 4 or >= 5 events.
 *
 * A campaign can keep growing after it first crosses the threshold, so the
 * report is refreshed while the campaign is still open and finalised once it
 * closes. Re-running this is cheap and makes no LLM calls.
 */
export async function generateReportIfNeeded(
  c: Campaign,
  force = false,
): Promise<string | null> {
  if (!force && !(await needsReport(c))) return null;
  // Refresh from the store so the report reflects the campaign as it stands.
  const latest = (await getCampaign(c.id)) ?? c;
  const events = await getCampaignEvents(c.id);
  if (events.length === 0) return null;

  const md = renderReport(latest, events);
  mkdirSync(OUT_DIR, { recursive: true });
  const path = join(OUT_DIR, `campaign-${c.id}.md`);
  writeFileSync(path, md);
  await markReportGenerated(c.id);
  return path;
}
